---
title: "Resources for learning R"
author: "Nicholas Tierney"
output: 
  html_document:
    theme: readable
    toc: true
    toc_float: true
---

# About {-}

This page provides a set of curated resources for learning concepts in R. The 
concepts are grouped in level 1 headers, that you can access through the 
floating table of contents.

# shiny

## Introductory

-   <https://mastering-shiny.org/basic-app.html>

    -   This section gets you started with the basics of a shiny app
    -   This from an in-progress book <https://mastering-shiny.org/> by Hadley Wickham, which goes from first steps, to handling issues in putting apps in production. The book is still being written, but is due to be finished by the end of 2020.

-   <https://shiny.rstudio.com/tutorial/>

    -   Provides a 2 hour video tutorial, with the links below being timestamped sections of the video where it discusses specific concepts
    -   Also links to other good tutorials

-   Publishing / deploying shiny apps

    -   <https://shiny.rstudio.com/deploy/>

-   Debugging shiny

-   <https://rstudio.com/resources/shiny-dev-con/debugging-techniques/>

-   <https://mastering-shiny.org/action-workflow.html>

-   <https://shiny.rstudio.com/articles/debugging.html>

-   Cheat sheet: https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf

-   Past workshops on {shiny}:

    -   <https://github.com/rstudio-education/intro-shiny-rmarkdown>
    -   <https://github.com/laderast/gradual_shiny>
    -   <https://github.com/jcheng5/rstudio2017-shiny-workshop/tree/master/slides>
    -   <https://github.com/rstudio-education/shiny-sdss18>

-   Many resources found via: <https://github.com/mitchelloharawild/shiny-intermediate-workshop>

# Reporting problems with your code

-   `reprex`: {rep}roducible {ex}amples

    -   (why reprex): <https://reprex.tidyverse.org/articles/articles/magic-reprex.html>
    -   How to reprex: <https://reprex.tidyverse.org/articles/articles/learn-reprex.html>

# Debugging in R

-   <https://adv-r.hadley.nz/debugging.html>

-   <https://jozef.io/r916-exploring-r-code-interactively/>

-   <https://rstudio-education.github.io/hopr/debug.html>

-   Using {debugonce}
    - An approach for using {recover}, to help track down errors across multiple functions:
    - <https://www.youtube.com/watch?v=M5n_2jmdJ_8>

-   RStudio IDE break-points to track down errors in code, particularly \> if you have multiple functions

    -   https://rstudio-education.github.io/hopr/debug.html\#break-points

# ggplot2

-   Introduction:

    -   https://r4ds.had.co.nz/data-visualisation.html
    -   https://r4ds.had.co.nz/graphics-for-communication.html

-   Detailed:
    -   https://ggplot2.tidyverse.org/
    -   https://ggplot2-book.org/

# Vectors

-   Detailed:
    -   https://adv-r.hadley.nz/vectors-chap.html

# Lists

-   Detailed:
    -   https://adv-r.hadley.nz/vectors-chap.html\#lists

# Dataframe vs a tibble

-   https://r4ds.had.co.nz/tibbles.html

# Functions

-   Detailed:

    -   https://adv-r.hadley.nz/functions.html

-   On "functional" programming

    -   https://adv-r.hadley.nz/fp.html

-   Using vs creating functions

# Tidying data

-   5 examples of long/wide to tidy

    -   Anscombe's quartet (wide to long): https://www.njtierney.com/post/2020/06/01/tidy-anscombe/
    
-   5 example of general tidying

# Xaringan slides

-   https://slides.yihui.org/xaringan/\#1

-   Enhancing slides:

    -   5 minute video: https://www.youtube.com/watch?v=vZMuu77ocMY&t=2s

    -   {xaringanthemer}:  https://pkg.garrickadenbuie.com/xaringanthemer/

    -   {xaringanExtra}: \> https://pkg.garrickadenbuie.com/xaringanExtra/

# Flexdashboard

-   https://rmarkdown.rstudio.com/flexdashboard/
