# shiny

Shiny is a really awesome way to enhance your R script, package, or method. Shiny turns these into 'apps', that people can interact with. You should consider using shiny if you want to create a way for people to interact with their data and produce output like a report or plots. See some more details below on getting started.

## Introductory

- https://mastering-shiny.org/basic-app.html
  - This section gets you started with the basics of a shiny app
  - This from an in-progress book <https://mastering-shiny.org/> by Hadley Wickham, which goes from first steps, to handling issues in putting apps in production. The book is still being written, but is due to be finished by the end of 2020.

- https://shiny.rstudio.com/tutorial/
  - Provides a 2 hour video tutorial, with the links below being timestamped sections of the video where it discusses specific concepts
  - Also links to other good tutorials

- Publishing / deploying shiny apps
  - https://shiny.rstudio.com/deploy/

- Debugging shiny
  - <https://rstudio.com/resources/shiny-dev-con/debugging-techniques/>
  - <https://mastering-shiny.org/action-workflow.html>
  - <https://shiny.rstudio.com/articles/debugging.html>

- [Cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf)

- Past workshops on {shiny}:
  - <https://github.com/rstudio-education/intro-shiny-rmarkdown>
  - <https://github.com/laderast/gradual_shiny>
  - <https://github.com/jcheng5/rstudio2017-shiny-workshop/tree/master/slides>
  - <https://github.com/rstudio-education/shiny-sdss18>

- Many resources found via: <https://github.com/mitchelloharawild/shiny-intermediate-workshop>
