# Spatial data

Spatial data analysis can be really different to anything else that you've done in R.  Fortunately, [recent awesome progress](https://www.r-consortium.org/blog/2017/01/03/simple-features-now-on-cran) has been made on the simple features R package, officially supported by the RConsortium, and authored by [Edzer Pebesma](https://github.com/edzer). The format of simple features is to adopt a standard dataframe format, where every row is a spatial feature, and the spatial features are described in a geometry list column. This is really fantastic, because it means that (for the most part), working with spatial data is very similar to working with regular dataframes, which is the bread and butter of analysis and data wrangling in R. 

In particular, simple features is designed to play nicely with [the tidyverse](https://tidyverse.org/), and accordingly plays well with ggplot2, dplyr, purrr, and so on. It's amazing. 

Here is a list of resources on using spatial data in R:

- The [R Spatial Blog](https://r-spatial.org/) is a great way to stay updated with the latest changes in simple features.

- [A blog post by Matt Strimas-Mackey](https://strimas.com/r/tidy-sf/) on how to use simple features with dplyr, tidyr, and ggplot2.

- [Mapping France at night](https://sharpsightlabs.com/blog/mapping-france-night/)

- [Spatial Pipelines](https://walkerke.github.io/2016/12/spatial-pipelines/)

- [Simple Features Vignettes](https://edzer.github.io/sfr/articles/)

- [Using simple features with ggraph](https://rpubs.com/cyclemumner/sf-ggraph)

- [A comparison of plotting in sp compared to sf](https://rpubs.com/cyclemumner/sf-plotting)

- [Geocomputation with R (a book)](https://geocompr.robinlovelace.net/)

- [The R Task View on Spatial Data](https://cran.r-project.org/web/views/Spatial.html)

- [Introduction to GIS with R](https://www.jessesadler.com/post/gis-with-r-intro/)

- [Steph de Silva-Stammel's blog post on resources for geospatial data and transport](https://www.stephdesilva.com/post/the-keys-to-the-kingdom/)

- [The `tmap` package provides a great rich way to build static and interactive spatial plots in a layered approach similar to ggplot2](https://github.com/mtennekes/tmap)

- [The `mapview` package provides functions to very quickly and conveniently create interactive visualisations of spatial data.](https://r-spatial.github.io/mapview/)

For more thoughts on R for spatial data analysis:

- [Michael Sumner's overview](https://mdsumner.github.io/2017/01/10/spatial-r-2017.html) of R's spatial capabilities for 2017.

For interactive visualisation of spatial data, I really like RStudio's [leaflet](https://rstudio.github.io/leaflet/), which is a port of the excellent [JavaScript leaflet library](https://leafletjs.com/) is my go to place. 

[ggmap](https://cran.r-project.org/web/packages/ggmap), is also great, as it produces static maps.