# Troubleshooting

To learn R effectively, you need to learn how to get unstuck with R. Remember that everyone, even the experienced R users, still get stuck and stumped. I've been programming with R for over 7 years and I regularly come across issues I can't solve. Sometimes they're complex, but more often than not, they are simple issues to do with typos, or me not using something correctly. As you get more confidence with using R, you will become faster at becoming unstuck.

## There's a problem with my R code

This post, [how to get unstuck with R](https://stat545.com/help-general.html), teaches a really good process to iterate through when going through the process of getting unstuck.

For other problems in R, try following this process:

### Phase 1: Typos + Spelling

- Check for typos. Do you have a spelling mistake?
- Are you missing an opening or closing bracket? (remember the three types of bracket `()`, `[]`, `{}`).
- Are you missing an opening / closing quote, `"` or `'`?
- Are you missing a comma? Or have you got an extra one?
- Did you leave a trailing `%>%` or `+` at the end of a line of code?
- Have you checked for typos again? 
- Check for typos one more time.
- Restart R

Repeat this process until you are sure these aren't the issue. I have, on several occasions, spent an entire day chasing an error, optimising my R code, doing a lot of work really, and the main issue was a missing comma.

### Phase Two: Google is your friend and so is R

- Copy and paste the error message into google. See what comes up.
- If that doens't work, try removing extra detail that might be project specific
- You can also try  [RSeek](https://rseek.org/), basically a google search that filters by R related content. 
- If it is related to a specific function, check that I'm using it correctly by reading the helpfile.
  - Write `?FUNCTION` into the console, and scroll through to the bottom to look at the examples. Check if you are using the function the right way. Then, read through the helpfile to check the inputs are right. For example, you might be giving a function the wrong input.
    - e.g., `mean(1,2,3)` vs `mean(c(1,2,3))` vs `mean(c("1", "2", "3"))`. The second one is the correct one, since `mean` takes a vector as input.

### Phase Three: Ask google again

- Ask google for help again, but this time try to ask about the problem you are solving. 
- "The google formula": "how to" (your problem/question) "rstats"
  - Examples: 
    - You are trying to calculate the mean in R with `mean(100, 102, 103)`, but your answer doens't make sense. You can google "How to calculate the mean in rstats"
    - `lm(Ozone ~ Solar.R)` returns: `Error in eval(predvars, data, env) : object 'Ozone' not found`. In response, google, "Using lm for linear model rstats" and look at the examples they use.

### Phase Four: Rubber Duck

- Try explaining the code to yourself. This is sometimes called "rubber duck debugging". This is where you place a rubber duck/inanimate object on your computer and explain, carefully, what you are doing. 
- Try explaining the code to a colleague. Like a rubber duck, but they can talk back.
- Try creating a [reproducible example](https://reprex.tidyverse.org/) to see if you can recreate the issue you are experiencing. This is really useful because it means that you can transport your problem very efficiently to someone else. Or, if you cannot reproduce the error, then it means there might be another issue, like referring to an object you created in another R session. It takes a bit of practice to create reproducible examples, see the chapter [reproducible examples]() for more detail.

## Asking for help

Remember that it is 100% OK and "the norm" to use resources like [Stack Overflow](https://stackoverflow.com), [Rstudio community](https://community.rstudio.com/), and other people's blog posts, to help you solve a problem.

If you're still a bit stuck after trying the process above, that's OK! I recommend posting a question in these two places (in order of preference):

- [RStudio community](https://community.rstudio.com/) - They provide a nice, friendly space to ask questions that don't necessarily fit into GitHub issues, bug reports, or Stack Overflow. 
- [StackOverflow](https://stackoverflow.com) - if you've specified a good [reproducible example](https://reprex.tidyverse.org/) here, there are good chances it will be able to be solved.

## Package install / library errors

Sometimes there are errors that appear when you install packages or load them with `library`. This [blog post](https://www.njtierney.com/post/2020/05/29/there-is-no-pkg/) helps address one of the variants of this error:

  - `Error in loadNamespace(name) : there is no package called 'here'`
  - `Error in library(here) : there is no package called 'here'`
  - `Warning in install.packages : package ‘emo’ is not available (for R version 3.6.2)`